### ISSUE TITLE
  There is no table with name "base_models" in the schema.

### ISSUE THREAD

**Issue by Khant-Nyar** [recca0120/laravel-erd#13]
i got error for this .how to solve it 
![Screenshot from 2024-09-21 21-50-35](https://github.com/user-attachments/assets/f0e68ad0-6566-4e76-83a2-3ec1d0a4f762)

**Comment by recca0120** [comment]
make BaseModel abstract

**Comment by Khant-Nyar** [comment]
i solved to create empty migration file,it may be need by my third party package to manage ACL,btw thaks @recca0120
