### ISSUE TITLE
OneToOne relations displayed as OneToMany relations

### ISSUE THREAD

**Issue by dmohns** [recca0120/laravel-erd#17]
In the example ERD there should be a OneToOne relation between (for example) `Car` and `Mechanic` as 

```php
class Mechanic extends Model
{
    public function car(): HasOne
    {
        return $this->hasOne(Car::class);
    }
```

and

```php
class Car extends Model
{
    public function mechanic(): BelongsTo
    {
        return $this->belongsTo(Mechanic::class);
    }
```

However, the demo shows a OneToMany ERD Relation

<img width="999" alt="image" src="https://github.com/user-attachments/assets/3b19821c-8c6c-40db-a1f9-9ee56c9b67c0">

**Comment by recca0120** [comment]
[erd-editor](https://github.com/dineug/erd-editor) supports two way to draw erd model
only use typescript's type can draw OneToMany relations ...

laravel-erd only implement sql to draw erd.
this issue needs make laravel-erd implement typescript's type

like this https://github.com/recca0120/laravel-erd/blob/main/src/Template/DDL.php
