### ISSUE TITLE
i use mysql and have error :  could not find driver (Connection: mysql, SQL: PRAGMA foreign_keys = ON;)

### ISSUE THREAD

**Issue by trihai306** [recca0120/laravel-erd#4]
at vendor\laravel\framework\src\Illuminate\Database\Connection.php:829
    825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    826▕                 );
    827▕             }
    828▕
  ➜ 829▕             throw new QueryException(
    830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    831▕             );
    832▕         }
    833▕     }

  1   vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:65
      PDOException::("could not find driver")

  2   vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:65
      PDO::__construct("sqlite::memory:", "root", Object(SensitiveParameterValue), [])

**Comment by recca0120** [comment]
when generate erd, this package will change database to sqlite. install sqlite extension can fix this issue

**Comment by baradhili** [comment]
umm but what if I am using mysql for the laravel db?

**Comment by recca0120** [comment]
see #6
