### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 near "AUTO_INCREMENT": syntax error

### ISSUE THREAD

**Issue by cars1n** [recca0120/laravel-erd#6]
I am currently using laravel sail with mysql as the db. Everything works in communication with my mysql db container. It can run migrations fine, make changes, etc... but when I try to run the php artisan erd:generate in my docker container I get a sqlite error? I have double checked .env file, config/database.php file, docker-compose.yml file, as well as clearing cache and running migrations but nothing has worked. Same error still appears.

# php artisan erd:generate

   PDOException 

  SQLSTATE[HY000]: General error: 1 near "AUTO_INCREMENT": syntax error

  at vendor/laravel/framework/src/Illuminate/Database/Schema/SqliteSchemaState.php:64
     60▕      */
     61▕     public function load($path)
     62▕     {
     63▕         if ($this->connection->getDatabaseName() === ':memory:') {
  ➜  64▕             $this->connection->getPdo()->exec($this->files->get($path));
     65▕ 
     66▕             return;
     67▕         }
     68▕ 

      +33 vendor frames 

  34  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by ThomasEnssner** [comment]
Did you use `php artisan schema:dump --prune` an any time.
To check this you now would have a file `database/schema/mysql-schema.sql`.

I think as this package uses an in memory sqlite driver, the mysql syntax in that file is not fully supported.

**Comment by c-tanner** [comment]
If you're like me (and others here) that have MySQL migrations that are incompatible with SQLite, you can work around this by modifying `vendor/recca0120/laravel-erd/src/Console/Commands/GenerateErd.php`:

1. Create a new temp DB (ex. `my_temp_db`). This can be blank.
2. Modify the following 2 lines in `GenerateErd::setupFakeDatabase()`:

```php
config(Arr::dot(array_map(static fn (array $config) => [
    'driver' => 'mysql', <-- change to mysql
    'database' => 'my_temp_db', <-- change to temp DB name
    'prefix' => $config['prefix'] ?? '',
    'foreign_key_constraints' => true,
    'busy_timeout' => null,
    'journal_mode' => null,
    'synchronous' => null,
], $this->backup['database.connections']), 'database.connections.'));
```

Might be worth a PR if the maintainers are open to it and I have some time to make this configurable.

**Comment by gmgarrison** [comment]
I'm also getting this error and have pruned migrations down to a schema dump.

**Comment by recca0120** [comment]
```bash
composer require recca0120/laravel-erd:dev-main --dev
```

change the config laravel-erd.php to

```php

/**
 *  for example 
 * your production database is 'testbench'
 */
 
 return [
    'uri' => env('LARAVEL_ERD_URI', 'laravel-erd'),
    'storage_path' => storage_path('framework/cache/laravel-erd'),
    'extension' => env('LARAVEL_ERD_EXTENSION', 'sql'),
    'middleware' => [],
    'binary' => [
        'erd-go' => env('LARAVEL_ERD_GO', '/usr/local/bin/erd-go'),
        'dot' => env('LARAVEL_ERD_DOT', '/usr/local/bin/dot'),
    ],
    'connections' => [
        // as same as your current database name
        'testbench' => [
            'driver' => 'mysql',
            'host' => '127.0.0.1',
            'port' => '3306',
            'database' => 'test', // <-- this is a fake database, don't set this to your production database or development database
            'username' => 'root',
            'password' => '',
            'unix_socket' => '',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => null,
            'options' => [],
        ]'
    ],
];
```

**Comment by dmohns** [comment]
I have been testing this for the past week using `dev-main`. Seems to be working great so far.

@recca0120 any chance for a new (versioned) release including this feature soon(-ish) 😉 ?
